{% set version = "8.0.0.6" %}

package:
  name: types-pyvmomi
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-pyvmomi/types-pyvmomi-{{ version }}.tar.gz
  sha256: 494114a0ff30fa9cfe80dbd940308757586c836717803d8cb8af90f4f3190932

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - types-enum34

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/pyVmomi-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pyvmomi
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
